### ISSUE TITLE
Given two node embedding, how to predict the relation embedding between them?

### ISSUE THREAD

**Issue by aqzheng** [DeepGraphLearning/KnowledgeGraphEmbedding#11]

**Comment by Edward-Sun** [comment]
To predict the relation, you can try all the available relations and see which gives the highest score.

To predict the relation embedding, you can calculate phase(r) by phase(t) - phase(h).

Please note that currently we don't use relation corruption in training. If you want to predict the relation or relation embedding. You should also corrupt the r in (h, r, t) triplets.
