### ISSUE TITLE
How to get the embeddings file of all the entities and relations?

### ISSUE THREAD

**Issue by Shengqiang-Zhang** [DeepGraphLearning/KnowledgeGraphEmbedding#13]
Hello, Zhiqing. I want to know how to get the embeddings file of all the entities and relations after training a RotatE model on some knowledge graph dataset? Like the glove word embeddings file.

**Comment by KiddoZhu** [comment]
Hi. You can find numpy dump of embeddings in `models/RotatE_*_0/`.
