### ISSUE TITLE
Some question about the test process.

### ISSUE THREAD

**Issue by zysforever** [DeepGraphLearning/KnowledgeGraphEmbedding#15]
When I tested the model by the command: CUDA_VISIBLE_DEVICES=0 python -u codes/run.py --do_test --cuda -init models/RotatE_countries_S3_0, it showed that "UnboundLocalError: local variable 'current_learning_rate' referenced before assignment". I'm a novice. Could you tell me how to solve it? I would appreciate it if you can help me. Looking forward to your reply.
![@7P(5DJE}O% QE)(L KFOBA](https://user-images.githubusercontent.com/20456940/67733100-51437a00-fa38-11e9-8b63-46f70a1d32b4.png)

**Comment by Edward-Sun** [comment]
Sorry, it's a bug. We just fixed it. Please pull and try again.

**Comment by zysforever** [comment]
> Sorry, it's a bug. We just fixed it. Please pull and try again.

Problem solved! Thank you very much!
