### ISSUE TITLE
typo MRR in README.md

### ISSUE THREAD

**Issue by leiloong** [DeepGraphLearning/KnowledgeGraphEmbedding#2]
Dataset | FB15k | FB15k-237 | wn18 | wn18rr
MRR | .797 ± .001 | **.949 ± .000** | **.337 ± .001** | .477 ± .001

The MRR of datasets FB15k-237 and wn18 should be swapped with each other.

**Comment by Edward-Sun** [comment]
This is our mistake. Thank you!
