### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by Bishnukuet** [DeepGraphLearning/KnowledgeGraphEmbedding#24]
Start Training......
  File "codes/run.py", line 101
    **save_variable_list,
     ^
SyntaxError: invalid syntax

-----------------------
Don't know what causing this error. Do you have any idea.

**Comment by Edward-Sun** [comment]
try Python 3?

**Comment by Bishnukuet** [comment]
Its already python 3.7.

**Comment by Edward-Sun** [comment]
Sorry about that. **save_variable_list means to expand the dictionary here. If it doesn't work in your Python interpreter, maybe you can re-write it as:

tmp_dict = {}
for key in save_variable_list:
	tmp_dict[key] = save_variable_list[key]
tmp_dict['model_state_dict'] = model.state_dict()
tmp_dict['optimizer_state_dict'] = optimizer.state_dict()

torch.save(tmp_dict,
           os.path.join(args.save_path, 'checkpoint')
)
