### ISSUE TITLE
Can't find log files

### ISSUE THREAD

**Issue by p6jain** [DeepGraphLearning/KnowledgeGraphEmbedding#25]
Hi!

I trained the model using the following command:
```
CUDA_VISIBLE_DEVICES=0 python -u codes/run.py --do_train --cuda --do_valid --do_test --data_path data/FB15k-237 --model RotatE -n 256 -b 1024 -d 1000 -g 24.0 -a 1.0 -adv -lr 0.0001 --max_steps 150000 **-save models/RotatE_FB15k-237** --test_batch_size 16 -de --cuda
```
and tested it using:
```
time CUDA_VISIBLE_DEVICES=1 python -u codes/run.py --do_test -init models/RotatE_FB15k-237/ --cuda  
```
I am not able to find the log files in  models/RotatE_FB15k-237/ folder. I am unsure what went wrong. Please help.

**Comment by Edward-Sun** [comment]
Hi Prachi,

Can you find the model checkpoint in models/RotatE_FB15k-237 directory before testing?

**Comment by p6jain** [comment]
Yes, there is one.

**Comment by Edward-Sun** [comment]
Hi Prachi,

I have no idea. Could you please try:

`CUDA_VISIBLE_DEVICES=1 python -u codes/run.py --do_test -init models/RotatE_FB15k-237/ --cuda`

without `time` again?

If it doesn't work, you can upload your checkpoint and I'll try to figure out the problem.
