### ISSUE TITLE
Hi,I want to

### ISSUE THREAD

**Issue by Aristomd** [DeepGraphLearning/KnowledgeGraphEmbedding#27]

**Comment by Aristomd** [comment]
I want to use your rotate code, entity vectors I have trained using the GCN method, I want to further use totate to train entity relationship vectors, but your code is to use embedding_range to evenly distribute the initialized entity and relationship vectors, and I have With entity vectors, how I make phases of relations uniformly distributed in [-pi, pi]

**Comment by Edward-Sun** [comment]
Hi,

You can use the sin and cos function to convert values in [-pi, pi] to phases.
