### ISSUE TITLE
Interpreting how does RotatE handle 1-N, N-N type relations...

### ISSUE THREAD

**Issue by agoel00** [DeepGraphLearning/KnowledgeGraphEmbedding#36]
Hi. Great work and repo. 
I was curious to know what is the geometrical interpretation when RotatE handles 1-N and N-N type relations.
For example, in TransH we know that the embeddings are projected onto a relation specific hyperplane to bypass this issue.

How is this handled in the complex plane of RotatE?

**Comment by Edward-Sun** [comment]
Hi, thanks for the good question. In RotatE, we don't consider 1-N, N-N type relations. This is a problem worth studying as future work.
