### ISSUE TITLE
confused about implementation of DistMult

### ISSUE THREAD

**Issue by junkangwu** [DeepGraphLearning/KnowledgeGraphEmbedding#41]
According to the model in `distmult` paper, $$score = h_s * M_r * h_o^T$$. However, in most papers about knowledge graph completion including the model in CompGCN, they are realized as a form of $$score = h_s * r * h_o^T$$. May I ask you about the insight behind your realization form?

**Comment by Edward-Sun** [comment]
The distmult model uses a diagonal matrix, so these two definitions are equivalent.
