### ISSUE TITLE
N-1 and 1-N relations

### ISSUE THREAD

**Issue by Walker-ZD** [DeepGraphLearning/KnowledgeGraphEmbedding#45]
&ensp;&ensp;Thanks for your work，I'm a beginner of KGE.
&ensp;&ensp;While reading this paper，I have a problem: for N-1 relation r, it should be  x1· r = y  and  x2· r = y，r corresponds to a counterclockwise rotation, so  x1  is close to  x2 , which has the same issue with TransE.
&ensp;&ensp;I'm not sure whether my understanding is true, it seems that RotatE can't model N-1 relation and 1-N relation properly.
&ensp;&ensp;Looking forword to your reply, thank you.

**Comment by Edward-Sun** [comment]
Yes, RotatE doesn't consider N-1 and 1-N relations.

**Comment by StrugglerDream** [comment]
Thanks for your reply. Now I wonder if there is a method to visualize RotatE.
    For example, if I train a dataset with TransE，maybe the dimension is 100. Then, for every entity vector, I can use t-SNE to reduce their dimension to 2 and plot these entity vectors in plane coordinate system. Theoretically, if two entities have similar meanings, they are close in plane coordinate system. It works in my experiment, and there are many clusters in picture.
   Considering that RotatE is modeled in complex space, each dimension includes real and imaginary parts. Maybe a n-dimension entity vector is stored in this form: [re1, re2, ......, ren, im1, im2, ......, imn ]，which can not directly use t-SNE to reduce dimision.
    I try to reduce the dimension of real and imaginary parts to 1 separately, and then plot them in plane coordinate system, but it's not work, maybe too much information was lost. Do you have any ideas? Thank you.

**Comment by StrugglerDream** [comment]
> Yes, RotatE doesn't consider N-1 and 1-N relations.
&ensp;&ensp;Thanks for your reply. Now I wonder if there is a method to visualize RotatE.
&ensp;&ensp;For example, if I train a dataset with TransE, maybe the dimension is 100. Then, for every entity vector, I can use t-SNE to reduce their dimension to 2 and plot these entity vectors in plane coordinate system. Theoretically, if two entities have similar meanings, they are close in plane coordinate system. It works in my experiment, and there are many clusters in picture.
&ensp;&ensp;Considering that RotatE is modeled in complex space, each dimension includes real and imaginary parts. Maybe an n-dimension entity vector is stored in this form: [re1, re2, ......, ren, im1, im2, ......, imn ], which can not directly use t-SNE to reduce dimision.
&ensp;&ensp;I try to reduce the dimension of real and imaginary parts to 1 separately, and then plot them in plane coordinate system, but it's not work, maybe too much information was lost. Do you have any ideas? Thank you.

**Comment by Walker-ZD** [comment]
> Yes, RotatE doesn't consider N-1 and 1-N relations.

&ensp;&ensp;Thanks for your reply. Now I wonder if there is a method to visualize RotatE.
&ensp;&ensp;For example, if I train a dataset with TransE, maybe the dimension is 100. Then, for every entity vector, I can use t-SNE to reduce their dimension to 2 and plot these entity vectors in plane coordinate system. Theoretically, if two entities have similar meanings, they are close in plane coordinate system. It works in my experiment, and there are many clusters in picture.
&ensp;&ensp;Considering that RotatE is constructed in complex space, each dimension includes real and imaginary parts. Maybe an n-dimension entity vector is stored in this form: [re1, re2, ......, ren, im1, im2, ......, imn ], which can not directly use t-SNE to reduce dimision.
&ensp;&ensp;I try to reduce the dimension of real and imaginary parts to 1 separately, and then plot them in plane coordinate system, but it's not work, maybe too much information was lost. Do you have any ideas? Thank you.

**Comment by Edward-Sun** [comment]
I think you should concatenate the dimension of real and imaginary and project it to 2.
