### ISSUE TITLE
hi，a priblem about multi GPU training

### ISSUE THREAD

**Issue by Zhangs996** [DeepGraphLearning/KnowledgeGraphEmbedding#46]
how can i  change the code  to do multi gpu training
怎么样才能用多个gpu进行训练呢，我用的我自己的数据集，报的是显存溢出，我的显存40G，数据量太大啦，请问可以怎么修改呢？谢谢

**Comment by Edward-Sun** [comment]
Please check GraphVite (https://github.com/DeepGraphLearning/graphvite) for large-scale multi-GPU training.
