### ISSUE TITLE
Regarding the direction  of the rotation

### ISSUE THREAD

**Issue by seldce** [DeepGraphLearning/KnowledgeGraphEmbedding#49]
In a paper, you mention that the direction must be counter clock wise. However image showing direction from head to tail in clockwise.  Is there any typo or I made some mistake.  It would be great, if you can put some insight on it. Thank you

**Comment by Edward-Sun** [comment]
Hi, the direction should be counter-clockwise because we follow the definition of complex numbers. The direction in the figure is wrong.
