### ISSUE TITLE
what is L3 regularization 

### ISSUE THREAD

**Issue by cheungdaven** [DeepGraphLearning/KnowledgeGraphEmbedding#6]
I am curious about the L3 regularization you use for complEx and DistMult? Can you give any references for it?

**Comment by cheungdaven** [comment]
Another quick question about the head and tail mode, are there any differences for Complex and DistMult in these two different modes?

**Comment by Edward-Sun** [comment]
Hi, this is the paper for L3 regularization, which proves to be effective for DistMult and ComplEx:
Lacroix, Timothée, Nicolas Usunier, and Guillaume Obozinski. "Canonical tensor decomposition for knowledge base completion." arXiv preprint arXiv:1806.07297 (2018).

The difference in head and tail mode is that in the head-batch mode, we predict the head entity given the tail entity and relation, while in the tail-batch mode, we predict the tail entity given the tail entity and relation.

Using these two modes helps save memory and computation.
